version: '3'
services:
  api_service:
    build: .
    container_name: api_service
    volumes:
      - ./:/Users/liangduanqi/shiye_data/GithubProject/api_project/
      - ./log:/log
    working_dir: /project/api_project/
    command: python service/api_service.py
    ports:
      - 8632:8632
    env_file:
      - docs/proj_env/env.list
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1